blank_issues_enabled: false
contact_links:
- name: 'ðŸ“š Create an Issue'
  about: You will be redirected to wso2/api-manager repository where all the APIM product suite issues are reported including Streaming Integrator releted issues.
  url: https://github.com/wso2/api-manager/issues/new/choose
- name: 'ðŸ’¬ Slack Channel'
  url: 'https://apim-slack.wso2.com/'
  about: |
    Chat with the community to get quick clarifications for your questions.
